// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardStatus } from "./CardStatus";

export type Card = { id: string, title: string, body: string, status: CardStatus, revision: number, position: number, source: string, deleted: boolean, createdAt: number, updatedAt: number, };
