// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestionOption } from "./QuestionOption";
import type { QuestionState } from "./QuestionState";

export type ChoiceQuestion = { id: string, conversationId: string, messageId: string, question: string, options: Array<QuestionOption>, state: QuestionState, selectedOption: number | null, answerText: string | null, };
