// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardStatus } from "./CardStatus";
import type { DiscussionState } from "./DiscussionState";

export type Discussion = { id: string, conversationId: string, messageId: string, cardId: string, title: string, reason: string, previousStatus: CardStatus, previousPosition: number, cardRevision: number, state: DiscussionState, automatic: boolean, };
