// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryProposal = { id: string, baseRevision: number, beforeMemory: string, memory: string, reason: string, state: string, };
