// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardReference } from "./CardReference";

export type Message = { id: string, conversationId: string, role: string, text: string, references: Array<CardReference>, createdAt: number, };
