// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotificationMode } from "./NotificationMode";
import type { NotificationPermission } from "./NotificationPermission";

export type NotificationSettings = { mode: NotificationMode, permission: NotificationPermission, };
