// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanAccount } from "./PlanAccount";

export type PlanStatus = { available: boolean, accounts: Array<PlanAccount>, active: PlanAccount | null, warning: string | null, };
