// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Proposal = { id: string, cardId: string, baseRevision: number, beforeTitle: string, beforeBody: string, title: string, body: string, reason: string, state: string, createdAt: number, };
