// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QuestionAnswer = { questionId: string, optionIndex: number | null, text: string | null, };
