// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MaterialKind } from "./MaterialKind";

export type ReferenceMaterial = { id: string, path: string, kind: MaterialKind, };
